//get logged user
exports.users = () => {
  return {
    id: 1243,
    uid: "dzm3WeCmK8",
    spotifyDisplayName: "Moses Vilchis",
    email: "mosesvilchis@gmail.com",
    tastemakerContactEmail: "mosesvilchis@gmail.com",
    image: "",
    processingNewData: false,
    complete: true,
    dateJoined: "2022-03-17 13:49:38",
    userType: null,
    paypalId: null,
    totalEarnings: null,
    status: "handled",
    isOnCuratorPage: null,
    enabled: true,
    active: true,
    instagramProfile: null,
    twitterProfile: null,
    facebookProfile: null,
    tiktokProfile: null,
    soundcloudProfile: null,
    primarySocialLink: null,
    referralLink: null,
    approved: false,
    preferredMusicStyle: null,
    inviteCode: null,
    twitchProfile: null,
    youtubeProfile: null,
    referralThisMonth: null,
    streakThisMonth: true,
    streaksCount: 12,
    spotifyLoggedIn: true,
  };
};
